version: '3'

services:

  nextcloud:
    image: nextcloud
    ports:
      -  8080:80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
    networks:
      - nextcloud_network

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextcloud_network

  locust:
    image: locustio/locust
    container_name: locust
    command: -f /locust-tasks/tasks.py --host=http://nextcloud
    ports:
      - "8089:8089"
    volumes:
      - ./locust-tasks:/locust-tasks
      - ./test_files:/test-data
    networks:
      - nextcloud_network

volumes:
  nextcloud_data:
  db_data:

networks:
  nextcloud_network:
    external: true
